# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - vet

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: 
        - github.com/shellscape